// Daily Challenge definitions – pool of 20 challenges
// Each challenge has a check function that receives round stats and returns progress increment

export const DAILY_CHALLENGES = [
    {
        key: 'words_15',
        name: 'Wort-Jäger',
        description: 'Besiege 15 Wörter in einer Runde',
        icon: '⚔️',
        target: 15,
        reward: 25,
        getProgress: (roundStats) => roundStats.wordsCompleted,
        type: 'single_round', // Must be done in one round
    },
    {
        key: 'words_25',
        name: 'Doppelter Kampf',
        description: 'Besiege insgesamt 25 Wörter heute',
        icon: '🗡️',
        target: 25,
        reward: 35,
        getProgress: (roundStats) => roundStats.wordsCompleted,
        type: 'cumulative', // Accumulates across rounds
    },
    {
        key: 'accuracy_95',
        name: 'Scharfschütze',
        description: 'Erreiche mindestens 95% Genauigkeit in einer Runde',
        icon: '🎯',
        target: 95,
        reward: 30,
        getProgress: (roundStats) => roundStats.accuracy,
        type: 'threshold', // Must reach target value
    },
    {
        key: 'accuracy_100',
        name: 'Perfekter Tag',
        description: 'Schaffe eine Runde mit 100% Genauigkeit',
        icon: '💯',
        target: 100,
        reward: 50,
        getProgress: (roundStats) => roundStats.accuracy,
        type: 'threshold',
    },
    {
        key: 'combo_15',
        name: 'Combo-Starter',
        description: 'Erreiche eine 15er Combo',
        icon: '🔗',
        target: 15,
        reward: 20,
        getProgress: (roundStats) => roundStats.maxCombo,
        type: 'threshold',
    },
    {
        key: 'combo_30',
        name: 'Combo-Meister',
        description: 'Erreiche eine 30er Combo in einer Runde',
        icon: '⛓️',
        target: 30,
        reward: 40,
        getProgress: (roundStats) => roundStats.maxCombo,
        type: 'threshold',
    },
    {
        key: 'wpm_20',
        name: 'Schnelle Finger',
        description: 'Tippe mit mindestens 20 WPM',
        icon: '⚡',
        target: 20,
        reward: 25,
        getProgress: (roundStats) => roundStats.wpm,
        type: 'threshold',
    },
    {
        key: 'wpm_30',
        name: 'Turbo-Tipper',
        description: 'Tippe mit mindestens 30 WPM in einer Runde',
        icon: '🚀',
        target: 30,
        reward: 45,
        getProgress: (roundStats) => roundStats.wpm,
        type: 'threshold',
    },
    {
        key: 'score_300',
        name: 'Punkte sammeln',
        description: 'Erreiche 300 Punkte in einer Runde',
        icon: '💎',
        target: 300,
        reward: 25,
        getProgress: (roundStats) => roundStats.score,
        type: 'threshold',
    },
    {
        key: 'score_600',
        name: 'Punkte-Jäger',
        description: 'Erreiche 600 Punkte in einer Runde',
        icon: '👑',
        target: 600,
        reward: 40,
        getProgress: (roundStats) => roundStats.score,
        type: 'threshold',
    },
    {
        key: 'no_damage',
        name: 'Eiserne Mauer',
        description: 'Beende eine Runde ohne Burgschaden',
        icon: '🏰',
        target: 1,
        reward: 35,
        getProgress: (roundStats) => roundStats.castleHp >= 100 ? 1 : 0,
        type: 'threshold',
    },
    {
        key: 'three_waves',
        name: 'Wellenbrecher',
        description: 'Überlebe alle 3 Wellen in einer Runde',
        icon: '🌊',
        target: 3,
        reward: 30,
        getProgress: (roundStats) => roundStats.wave,
        type: 'threshold',
    },
    {
        key: 'play_3_rounds',
        name: 'Fleißig üben',
        description: 'Spiele heute 3 Runden',
        icon: '📝',
        target: 3,
        reward: 20,
        getProgress: () => 1, // Each round = +1
        type: 'cumulative',
    },
    {
        key: 'play_5_rounds',
        name: 'Viel-Spieler',
        description: 'Spiele heute 5 Runden',
        icon: '🎮',
        target: 5,
        reward: 35,
        getProgress: () => 1,
        type: 'cumulative',
    },
    {
        key: 'words_total_40',
        name: 'Wort-Marathon',
        description: 'Besiege insgesamt 40 Wörter heute',
        icon: '🏃',
        target: 40,
        reward: 40,
        getProgress: (roundStats) => roundStats.wordsCompleted,
        type: 'cumulative',
    },
    {
        key: 'no_errors_5',
        name: 'Fehlerfreie Serie',
        description: 'Besiege 5 Wörter nacheinander ohne Fehler',
        icon: '✨',
        target: 5,
        reward: 30,
        getProgress: (roundStats) => roundStats.maxCombo >= 5 && roundStats.accuracy >= 100 ? 5 : 0,
        type: 'threshold',
    },
    {
        key: 'fast_and_accurate',
        name: 'Schnell & Präzise',
        description: '20+ WPM und 90%+ Genauigkeit in einer Runde',
        icon: '🌟',
        target: 1,
        reward: 35,
        getProgress: (roundStats) => (roundStats.wpm >= 20 && roundStats.accuracy >= 90) ? 1 : 0,
        type: 'threshold',
    },
    {
        key: 'high_combo_accurate',
        name: 'Meister der Kontrolle',
        description: '20er Combo und 95%+ Genauigkeit',
        icon: '🎖️',
        target: 1,
        reward: 40,
        getProgress: (roundStats) => (roundStats.maxCombo >= 20 && roundStats.accuracy >= 95) ? 1 : 0,
        type: 'threshold',
    },
    {
        key: 'improve_wpm',
        name: 'Persönliche Bestleistung',
        description: 'Verbessere dein WPM gegenüber dem Durchschnitt',
        icon: '📈',
        target: 1,
        reward: 30,
        getProgress: (roundStats) => roundStats.wpm > (roundStats.averageWPM || 0) ? 1 : 0,
        type: 'threshold',
    },
    {
        key: 'survivor',
        name: 'Überlebenskünstler',
        description: 'Beende eine Runde mit weniger als 50 HP',
        icon: '💪',
        target: 1,
        reward: 25,
        getProgress: (roundStats) => (roundStats.castleHp > 0 && roundStats.castleHp < 50) ? 1 : 0,
        type: 'threshold',
    },
];

// Get today's challenge using date as seed for consistent daily selection
export function getTodaysChallenge() {
    const today = new Date();
    const seed = today.getFullYear() * 10000 + (today.getMonth() + 1) * 100 + today.getDate();
    const index = seed % DAILY_CHALLENGES.length;
    return DAILY_CHALLENGES[index];
}

export function getTodayDateString() {
    const today = new Date();
    return today.toISOString().split('T')[0]; // YYYY-MM-DD
}
